- name: "Install Fish Shell"
  hosts: localhosts
  connection: local
  become: true
  gather_facts: false

  tasks:
    - name: "Install dependencies."
      register: aptout
      apt:
        state: latest
        update_cache: true
        name:
          - cmake
          - libncurses5-dev
          - libncursesw5-dev

    - name: "Install Fish Source."
      get_url:
        url: https://github.com/fish-shell/fish-shell/releases/download/3.7.1/fish-3.7.1.tar.xz
        dest: /tmp/fish.tar.xz

    - name: "Uncompress Tarball."
      unarchive: 
        src: /tmp/fish.tar.xz
        dest: /tmp/

    - name: "Make Build Folder."
      command:
        cmd: mkdir build
        chdir: /tmp/fish-3.7.1

    - name: "Install Fish."
      shell:
        cmd: cmake .. && make && make install
        chdir: /tmp/fish-3.7.1/build/

    - name: "Remove Fish Tarball."
      file:
        path: /tmp/fish-3.7.1.tar.xz
        state: absent

    - name: "Remove Build Files."
      file:
        path: /tmp/fish.tar.xz
        state: absent

    - name: "Download fzf."
      register: aptout
      get_url:
        url: https://github.com/junegunn/fzf/releases/download/0.45.0/fzf-0.45.0-linux_amd64.tar.gz
        dest: /tmp/fzf.tar.gz
    - debug: var=aptout

    # OnlyRoot()
# [LinuxProbe(), x86Probe(), DebianProbe(), WhichProbe("make")]
# Builds `fish` from source on Debian-based systems as well as zoxide and fzf. The last two are due to plugins from my configuration.

- name: "Install fish shell"
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: "Install build packages"
      register: aptout
      apt:
        state: latest
        update_cache: true
        name:
          - cmake
          - libncurses5-dev
          - libncursesw5-dev

    - name: Download Fish Source
      get_url:
        url: https://github.com/fish-shell/fish-shell/releases/download/3.7.1/fish-3.7.1.tar.xz
        dest: /tmp/fish.tar.xz

    - name: "Uncompress Tarball"
      unarchive:
        src: /tmp/fish.tar.xz
        dest: /tmp/

    - name: "Make Build Folder"
      command:
        cmd: mkdir build
        chdir: /tmp/fish-3.7.1/

    - name: "Install Fish"
      shell:
        cmd: cmake .. && make && make install
        chdir: /tmp/fish-3.7.1/build/

    - name: "Remove Fish Tarball"
      file:
        path: /tmp/fish.tar.xz
        state: absent

    - name: "Remove Fish Build Files"
      file:
        path: /tmp/fish-3.7.1/
        state: absent

    - name: "Download fzf"
      register: aptout
      get_url:
        url: https://github.com/junegunn/fzf/releases/download/0.45.0/fzf-0.45.0-linux_amd64.tar.gz
        dest: /tmp/fzf.tar.gz
    - debug: var=aptout

    - name: "Unpack fzf to /usr/local/bin/"
      register: aptout
      unarchive:
        src: /tmp/fzf.tar.gz
        dest: /usr/local/bin
    - debug: var=aptout

    - name: "Remove fzf"
      register: aptout
      file:
        path: /tmp/fzf.tar.gz
        state: absent
    - debug: var=aptout

    - name: Add fish as valid shell
      shell:
        cmd: echo /usr/local/bin/fish >> /etc/shells
