#!/bin/bash

wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2

if [ ! -d "/opt/gcc-arm-none-eabi" ]; then
    mkdir "/opt/gcc-arm-none-eabi"
    sudo tar xjf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 -C /opt/gcc-arm-none-eabi
else 
    echo "gcc-arm-none-eabi already exists!"
fi

rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2


